auth/urls.py
# auth/auth/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuario/', include('usuario.urls')),  # Inclua o aplicativo usuario
    path('',include('home.urls'))
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('menu/',views.home, name='home'),
    path('pesquisar_sala/',views.pesquisar_sala, name = 'pesquisar_sala'), 
    path('video_sala/<str:id_sala>/',views.video_sala, name = 'video_sala'),
    path('pavilhao/<str:numero_pavilhao>/',views.pavilhao,name='pavilhao'),
    path('', views.index, name='index'),
    path('deslogar/',views.deslogar, name='deslogar')

]

usuario/urls.py
# auth/usuario/urls.py
from django.urls import path
from . import views
from .views import admin_template_view


urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('painel/', views.painel_view, name='painel'),
    path('adm/templetes/adm/', admin_template_view, name='admin_template'),
]

home/models.py
from django.db import models

# Create your models here.

usuario/models.py
from django.db import models
from django.core.exceptions import ValidationError


# Create your models here.

class Curso (models.Model):
    nome = models.CharField(max_length=255)
    
    def __str__(self):
        return self.nome

class Sala (models.Model):
    PAVILHAO_CHOICES = [
        ('1', 'Pavilhão 01'),
        ('2', 'Pavilhão 02'),
    ]

    pavilhao = models.CharField(max_length=1,choices=PAVILHAO_CHOICES)    
    numero = models.IntegerField()
    url = models.CharField(max_length=250)
    
    def __str__(self) :
        return f'Sala N°{self.numero} | Pavilhão N° {self.pavilhao}'
    
class Dias (models.Model):
    
    DIAS_CHOICES = [
        ('1','Domingo'),
        ('2', 'Segunda Feira'),
        ('3', 'Terça Feira'),
        ('4', 'Quarta Feira'),
        ('5','Quinta Feira'),
        ('6', 'Sexta Feira'),
        ('7', 'Sábado'),
    ]
    
    dia = models.CharField(max_length=1,choices=DIAS_CHOICES)
    
    def __str__(self) -> str:
        return self.get_dia_display()
    
    def get_number_day(self):
        return self.dia
class CronogramaSala (models.Model):
    
    dias = models.ManyToManyField(Dias)
    sala = models.ForeignKey(Sala, on_delete=models.CASCADE)
    
    def __str__(self) :
        # Obter os nomes dos dias
        nomes_dias = ', '.join([dia.get_dia_display() for dia in self.dias.all()])
        return f'{nomes_dias} | {self.sala}'
class RegistroCurso(models.Model):
    
    TURNO_CHOICES = [
        ('manha', 'Manhã'),
        ('tarde', 'Tarde'),
        ('noite', 'Noite')
    ]
    
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)
    semestre = models.IntegerField()
    turno = models.CharField(max_length=5, choices=TURNO_CHOICES)
    sala = models.ManyToManyField(CronogramaSala)
    
class AtivarPesquisaSalas(models.Model):
    ativado = models.BooleanField(default=False)

    def __str__(self):
        return "Pesquisa de Salas Ativada" if self.ativado else "Pesquisa de Salas Desativada"
    

    def save(self, *args, **kwargs):
        if not self.pk and AtivarPesquisaSalas.objects.exists():
            raise ValidationError('Já existe um registro de AtivarPesquisaSalas.')
        super(AtivarPesquisaSalas, self).save(*args, **kwargs)

class Contador (models.Model):
    sala = models.ForeignKey(Sala, on_delete=models.CASCADE)
    data = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.sala} em {self.data.strftime("%Y-%m-%d %H:%M:%S")}'

usuario/forms.py
from django import forms
from .models import Dias

class DiasForm(forms.ModelForm):
    class Meta:
        model = Dias
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Obter os valores de 'dia' já existentes no banco de dados
        dias_existentes = Dias.objects.values_list('dia', flat=True)
        # Filtrar choices para remover os já existentes
        self.fields['dia'].choices = [
            choice for choice in Dias.DIAS_CHOICES if choice[0] not in dias_existentes
        ]

home/views.py
from django.shortcuts import redirect, render

from django.contrib.messages import constants
from django.contrib import messages

from usuario.models import AtivarPesquisaSalas, Contador, Sala,Curso,RegistroCurso

from django.urls import reverse
from django.contrib.auth import logout

import datetime


def home(request):
    status_pesquisa_salas = AtivarPesquisaSalas.objects.all().first().ativado
    
    return render(request,'menu.html',{"status_pesquisa_salas":status_pesquisa_salas})

def pesquisar_sala(request):
    cursos = Curso.objects.all()
    turnos = RegistroCurso.TURNO_CHOICES

    context = {
        'cursos': cursos,
        'turnos': turnos
    }

    if request.method == 'POST':
        semestre = request.POST['semestre']
        curso = request.POST['curso']
        turno = request.POST['turno']
        
        # Obtendo o dia da semana atual
        dia_semana = datetime.datetime.today().weekday()
        # Mapear para o formato do banco de dados (Django começa com 0 para segunda-feira)
        dias_mapping = {
            0: '2',  # Segunda-feira
            1: '3',  # Terça-feira
            2: '4',  # Quarta-feira
            3: '5',  # Quinta-feira
            4: '6',  # Sexta-feira
            5: '7',  # Sábado
            6: '1',  # Domingo
        }
        dia_atual = dias_mapping[dia_semana]
        
        try:
            # Filtrar RegistroCurso com base nos critérios
            registros = RegistroCurso.objects.filter(
                curso=curso,
                turno=turno,
                semestre=semestre
            )
            
            # Verificar o cronograma das salas para o dia atual
            for registro in registros:
                for cronograma in registro.sala.all():
                    if cronograma.dias.filter(dia=dia_atual).exists():
                        # Encontrou a sala no dia atual
                        return redirect(reverse('video_sala', kwargs={'id_sala': cronograma.sala.pk}))
            
            # Se nenhum registro corresponder ao dia atual
            messages.add_message(request, constants.ERROR, "Sala não encontrada para o dia atual")

        except RegistroCurso.DoesNotExist:
            messages.add_message(request, constants.ERROR, "Registro de curso não encontrado")
    
    return render(request, 'pesquisarSala.html', context)


def index (request):
    
    return render(request, 'index.html')

def video_sala (request,id_sala):
    sala = Sala.objects.get( pk = id_sala )
    
    try:
        Contador.objects.create(sala=sala)
    except:
        pass
    
    return render (request, 'videoSala.html',{"sala":sala})

def pavilhao (request,numero_pavilhao):
    
    salas = Sala.objects.filter(pavilhao = numero_pavilhao)
    
    return render (request,'pavilhao.html',{'salas':salas,'numero_pavilhao':numero_pavilhao })


def deslogar(request):
    logout(request)
    return redirect("/")

usuario/views.py
# auth/usuario/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('painel')  # Redireciona para a página do painel após o login
        else:
            return HttpResponse('Login invalido')
    return render(request, 'adm.html')

@login_required(login_url='login')
def painel_view(request):
    
    if request.method == 'POST':
        video = request.POST['video_url']
        sala = request.POST['sala']
        curso = request.POST['curso']
        turma = request.POST['turma']
        
        print(video,sala,curso,turma)
    return render(request, 'painel.html')


def admin_template_view(request):
    # Lógica para renderizar o template admin
    return render(request, 'adm.html', context={})

home/templates/index.html
<!DOCTYPE html>
<html lang="pt-Br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Menu Pricipal</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
        integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
</head>

<body>
    <main>
        <div class="pricipal">
            <h1 class="text-center">Precisa de ajuda para localizar a sua sala?</h1>
            <div class="botao">
                <a class="btn btn-primary btn-lg btn-block" href="{% url 'home' %}">Iniciar</a>
            </div>
        </div>
    </main>
    
    <div class="icon w-100 d-flex justify-content-end px-5">
        <a href="\admin\"><i class="fa-solid fa-user" style="color: #ffffff9a;"></i></a>
    </div>
    
   

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
</body>

</html>

home/templates/menu.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-Br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>menu</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
</head>

<body>
    <main>
        <div class="pricipal">
            <h1 class="text-center">MENU</h1>
            <div class="botoes">
                <a class="btn btn-primary btn-lg btn-block" href="{% url 'pavilhao' 1 %}">Pavilhão 01</a>
                <a class="btn btn-primary btn-lg btn-block" href="{% url 'pavilhao' 2 %}">Pavilhão 02</a>
                
                <a class="btn btn-primary btn-lg btn-block" {% if status_pesquisa_salas %}  href="{% url 'pesquisar_sala' %}" 
                {% else %} 
                  style="display: none;" 
                {% endif %}>
                Não sei minha sala de aula
             </a>
                
            </div>
        </div>
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>


</body>


</html>

home/templates/pavilhao.html
<!DOCTYPE html>
<html lang="pt-Br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PAVILHÃO 01</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
    </head>

<body>
    <main>
        <div class="pricipal">
            <h1 class="text-center titulo">PAVILHÃO 0{{numero_pavilhao}}</h1>
            <div class="container mt-5">
                <div class="row">
                    {% for sala in salas %}
                        <div class="col-12 col-md-4 mb-3">
                            <a class="btn btn-primary btn-lg btn-block" href="{% url 'video_sala' sala.pk %}">Sala {{ sala.numero }}</a>
                        </div>
                    {% endfor %}
                </div>
            </div>
            
            
        
    </main>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
</body>



</html>


</html>

home/templates/pesquisarSala.html
<!DOCTYPE html>
<html lang="pt-Br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pesquisar sala</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
</head>

<body>
    <main>
        <div class="pricipal">
            <h1 class="text-center">Pesquisar sala</h1>
            
            {% for mensagem in messages %}
                <div class="{{mensagem.tags}}" role="alert">
                    {{mensagem}}
                </div>
            {% endfor %}

            <form id="meuFormulario" action="" method="post">{% csrf_token %}
                <div class="pesquisa">
                    <label for="curso">Curso</label>
                    <select id="curso" name="curso">
                        {% for curso in cursos  %}
                            <option value="{{curso.pk}}">{{curso}}</option>
                        {% endfor %}
                    </select>

                    <label for="turno">Turno</label>
                    <select id="turno" name="turno">
                        {% for key,value in turnos  %}
                        <option value="{{key}}">{{value}}</option>

                        {% endfor %}
                    </select>

                    <label for="semestre">Semestre</label>
                    <select id="semestre" name="semestre">

                        <option value="1">1º</option>
                        <option value="2">2º</option>
                        <option value="3">3º</option>
                        <option value="4">4º</option>
                        <option value="5">5º</option>
                        <option value="6">6º</option>
                        <option value="7">7º</option>
                        <option value="8">8º</option>
                        <option value="9">9º</option>
                        <option value="10">10º</option>

                    </select>
                </div>

            </form>
            <button form="meuFormulario" class="btn btn-primary btn-lg btn-block mt-5">Pesquisar</button>
        </div>

    </main>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
    
    <script>
        document.addEventListener("DOMContentLoaded", function() {
            const messages = document.querySelectorAll('.alert');
            messages.forEach(function(message) {
                setTimeout(function() {
                    message.style.transition = "opacity 1s";
                    message.style.opacity = "0";
                    setTimeout(function() {
                        message.remove();
                    }, 1000);
                }, 5000);
            });
        });
    </script>
</body>
</html>

home/templates/videoSala.html
{% load filtros %}

<!DOCTYPE html>
<html lang="pt-Br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Caminho até sua sala</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
</head>

<body>
    <main>
        <div class="pricipal">
            <h1 class="text-center">Caminho até sua sala</h1>
            <p>{{sala.get_pavilhao_display}}</p>
            <p>Sala N° {{sala.numero}}</p>
            <iframe width="400" height="300" src="https://www.youtube.com/embed/{{sala.url|extrair_id_do_video}}"
                title="YouTube video player" frameborder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
        </div>
        <a href="/" class="btn btn-primary mt-5">Voltar para a tela inicial</a>
    </main>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
</body>

</html>

usuario/templates/adm.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>login adm</title>
  <link rel="stylesheet" href="{% static 'usuario/css/adm.css' %}">
</head>

<body>
  <div class="login-container">
    <h2>Login</h2>
    <form method="POST">
      {% csrf_token %}
      <div class="form-group">
        <label for="username"><i class="fa-solid fa-user" style="color: #000000;"></i> Usuario</label>
        <input type="text" id="username" name="username" required>
      </div>
      <div class="form-group">
        <label for="password"><i class="fa-solid fa-key" style="color: #000000;"></i> Senha</label>
        <input type="password" id="password" name="password" required>
      </div>
      <div class="botao">
        <button type="submit">Entrar</button>
      </div>
    </form>
  </div>
</body>

</html>

usuario/templates/cursos.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>cursos</title>
    <link rel="stylesheet" href="painel.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
        integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>
    <style>
        i{
            cursor: pointer;
        }
    </style>
    <header>
        <div class="menu">
            <div class="img">
                <img src="R.png" alt="" width="200px">
            </div>
            <div class="links">
                <a href="cursos.html">cursos</a>
                <a href="painel.html">Videos</a>
                <a href="../principal/index.html">tela inicial</a>
            </div>
        </div>
    </header>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">cursos</th>
                <th scope="col">turno</th>
                <th scope="col">semestre</th>
                <th scope="col">Editar</th>
                <th scope="col">Excluir</th>

            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">1</th>
                <td>Mark</td>
                <td>Otto</td>
                <td>@mdo</td>
                <td><i class="fa-solid fa-pen" style="color: #005eff;"></i></td>
                <td><i class="fa-solid fa-trash" style="color: #ff0000;"></i></td>
            </tr>

        </tbody>
    </table>







    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
</body>

</html>

usuario/templates/painel.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Painel adm</title>
    <link rel="stylesheet" href="{% static 'usuario/css/painel.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
    integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>

    <header>
        <div class="menu">
            <div class="img">
                <img src="{% static 'usuario/img/R.png' %}" alt="" width="200px">
            </div>
            <div class="links">
                <a href="cursos.html">cursos</a>
                <a href="painel.html">painel</a>
                <a href="../principal/index.html">tela inicial</a>
            </div>
        </div>
    </header>
    <div class="container">
        <div class="admin-panel">
            <h2>Painel do Administrador</h2>
            <form method="POST"> {% csrf_token %}
                <div class="form-group">
                    <label for="video-url">URL do Vídeo (YouTube)</label>
                    <input type="text" id="video-url" name="video_url" required>
                </div>
                <div class="form-group">
                    <label for="student-room">Sala</label>
                    <input type="text" id="student-room" name="sala" required>
                </div>
                <div class="form-group">
                    <label for="student-course">Curso</label>
                    <input type="text" id="student-course" name="curso" required>
                </div>
                <div class="form-group">
                    <label for="student-class">Turma</label>
                    <input type="text" id="student-class" name="turma" required>
                </div>
                <button type="submit">Cadastrar Vídeo</button>
            </form>
        </div>
    </div>
</body>

</html>